--Câu 1:
CREATE DATABASE QLSach
ON PRIMARY
(
	NAME = 'QLSach_Data',
	FILENAME = 'T:\QLTV\QLSach_Data.mdf',
	SIZE = 20 MB,
	MAXSIZE = 40 MB,
	FILEGROWTH = 1 MB
)
LOG ON
(
	NAME = 'QLSach_Log',
	FILENAME = 'T:\QLTV\QLSach_Log.ldf',
	SIZE = 6 MB,
	MAXSIZE = 8 MB,
	FILEGROWTH = 1 MB	
)
GO
--Câu 2:
--a)
CREATE DATABASE QLBH
ON PRIMARY
(
	NAME = 'QLBH_data1',
	FILENAME='E:\On Thi\QLBH_data1.mdf',
	SIZE = 10 MB,
	MAXSIZE = 40 MB,
	FILEGROWTH = 1 MB
)
LOG ON
(
	NAME = 'QLBH_log',
	FILENAME = 'E:\On Thi\QLBH_log.ldf',
	SIZE = 6 MB,
	MAXSIZE = 8	MB,
	FILEGROWTH = 1 MB
)
GO
--c)
ALTER DATABASE QLBH ADD FILEGROUP DuLieuQLBH
GO
--d)
ALTER DATABASE QLBH
ADD FILE
(
	NAME = 'QLBH_data2',
	FILENAME = 'E:\On Thi\QLBH_data2.ndf',
	SIZE = 6 MB,
	MAXSIZE = 8 MB,
	FILEGROWTH = 1 MB
)
TO FILEGROUP DuLieuQLBH
GO
--f)
ALTER database QLBH	SET	READ_ONLY
GO
sp_helpDb
GO
ALTER DATABASE QLBH SET READ_WRITE
GO
--g)
ALTER DATABASE QLBH
MODIFY FILE
(
	NAME = 'QLBH_data1',
	SIZE = 50 MB
)
GO
ALTER DATABASE QLBH
MODIFY FILE
(
	NAME = 'QLBH_log',
	SIZE = 10 MB
)
GO
--Câu 3:
--a)
CREATE DATABASE QLSV
GO
USE QLSV
GO
CREATE TABLE LOP
(
	MaLop CHAR(5) PRIMARY KEY,
	TenLop NVARCHAR(30) NOT NULL,
	SiSoDuKien INT,
	NgayKhaiGiang DATETIME
)
GO
CREATE TABLE SINHVIEN
(
	MaSV CHAR(5) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATETIME,
	MaLop CHAR(5) CONSTRAINT FK_MaLop_SV FOREIGN KEY REFERENCES dbo.LOP(MaLop)
)
GO
CREATE TABLE MONHOC
(
	MaMH CHAR(5) PRIMARY KEY,
	TenMH NVARCHAR(30),
	SoTC INT	
)
GO
CREATE TABLE KETQUA
(
	MaSV CHAR(5) NOT NULL,
	MaMH CHAR(5) NOT NULL,
	Diem REAL,
	CONSTRAINT PK_KQ PRIMARY KEY(MaSV,MaMH),
	CONSTRAINT FK_MaSV_KQ FOREIGN KEY (MaSV) REFERENCES dbo.SINHVIEN(MaSV),
	CONSTRAINT FK_MaMH_KQ FOREIGN KEY (MaMH) REFERENCES dbo.MONHOC(MaMH)
)
GO
--e)
ALTER DATABASE QLSV MODIFY NAME = QLHS
GO
--f)
DROP DATABASE QLHS
GO	