--Bài tập 1:
--Câu 3:
--a)
CREATE DATABASE QUANLY_BANHANG
GO
USE QUANLY_BANHANG
GO
CREATE TABLE NHOMSANPHAM
(
	MaNhom CHAR(5) PRIMARY KEY,
	TenNhom NVARCHAR(30),
	)
GO
CREATE TABLE NHACUNGCAP
(
	MaNCC INT PRIMARY KEY,
	TenNCC NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50),
	Phone VARCHAR(24),
	SoFax VARCHAR(24),
	DCMail VARCHAR(50)
)
GO
CREATE TABLE SANPHAM
(
	MaSP INT PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(50),
	DonViTinh NVARCHAR(20),
	DonGia MONEY CHECK (DonGia > 0),
	SLTon INT CHECK (SLTon > 0),
	MaNCC INT,
	MaNhom CHAR(5)
)
GO
CREATE TABLE KHACHHANG
(
	MaKH CHAR(5) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	LoaiKH NVARCHAR(3) CHECK (LoaiKH IN ('VIP', 'TV', 'VL')),
	DiaChi NVARCHAR(50),
	Phone VARCHAR(24),
	SoFax VARCHAR(24),
	DCMail VARCHAR(50),
	DiemTL INT CHECK (DiemTL >= 0)
)
GO
CREATE TABLE CT_HOADON
(
	MaHD INT NOT NULL,
	SoLuong INT CHECK (SoLuong > 0),
	DonGia MONEY,
	ChietKhau MONEY CHECK (ChietKhau > 0),
	MaSP INT NOT NULL
)
GO
CREATE TABLE HOADON
(
	MaHD INT NOT NULL,
	NgayLapHD DATETIME CHECK (NgayLapHD >=GETDATE()),
	NgayGiao DATETIME,
	NoiChuyen NVARCHAR(50) NOT NULL,
	MaKH CHAR(5)
)
GO
--b)
ALTER TABLE dbo.KHACHHANG
ADD PRIMARY KEY (MaKH)
GO
ALTER TABLE dbo.HOADON
ADD PRIMARY KEY (MaHD)
GO
ALTER TABLE dbo.CT_HOADON
ADD PRIMARY KEY (MaHD)
GO
--c)
ALTER TABLE dbo.HOADON
ADD FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH)
GO
ALTER TABLE dbo.HOADON
ADD FOREIGN KEY (MaHD) REFERENCES dbo.CT_HOADON(MaHD)
GO
ALTER TABLE dbo.CT_HOADON
ADD CONSTRAINT FK_CT_SP FOREIGN KEY (MaSP) REFERENCES dbo.SANPHAM(MaSP)
GO
ALTER TABLE dbo.SANPHAM
ADD CONSTRAINT FK_NCC FOREIGN KEY (MaNCC) REFERENCES dbo.NHACUNGCAP(MaNCC)
GO
ALTER TABLE dbo.SANPHAM
ADD CONSTRAINT FK_NHOMSP FOREIGN KEY (MaNhom) REFERENCES dbo.NHOMSANPHAM(MaNhom)
GO
--d)
ALTER TABLE dbo.SANPHAM
ADD CONSTRAINT CK_DonGia CHECK (DonGia > 0)
GO
ALTER TABLE dbo.SANPHAM
ADD CONSTRAINT CK_SLTon CHECK (SLTon > 0)
GO
ALTER TABLE dbo.HOADON
ADD CONSTRAINT CK_NgayLapHD CHECK (NgayLapHD >= GETDATE())
GO
ALTER TABLE dbo.CT_HOADON
ADD CONSTRAINT CK_SoLuong CHECK (SoLuong > 0)
GO
ALTER TABLE dbo.CT_HOADON
ADD CONSTRAINT CK_ChietKhau CHECK (ChietKhau >= 0)
GO
ALTER TABLE dbo.KHACHHANG
ADD CONSTRAINT CK_LoaiKH CHECK (LoaiKH='VIP' OR LoaiKH='TV' OR LoaiKH='VL')
GO
ALTER TABLE dbo.KHACHHANG
ADD CONSTRAINT CK_DiemTL CHECK (DiemTL >= 0)
GO
ALTER TABLE dbo.HOADON
ADD CONSTRAINT DF_NgayLapHD DEFAULT (GETDATE()) FOR NgayLapHD
GO
--e)
ALTER TABLE dbo.HOADON
ADD LoaiHD CHAR(1) NULL
GO
ALTER TABLE dbo.HOADON
ADD CONSTRAINT CK_LoaiHD
CHECK (LoaiHD='N' OR LoaiHD='X' OR LoaiHD='C' OR LoaiHD='T')
GO
ALTER TABLE dbo.HOADON
ADD CONSTRAINT DF_LoaiHD DEFAULT ('N') FOR LoaiHD
GO
--f)
ALTER TABLE dbo.HOADON
ADD CONSTRAINT CK_NgayGiao CHECK (NgayGiao >= NgayLapHD)
GO