CREATE DATABASE QLBH
ON
PRIMARY ( NAME=QLBHData,
FILENAME='F:\Bai thuc hanh\CSDL\QLBH.mdf',
SIZE=10MB,
MAXSIZE=15MB,
FILEGROWTH=20%)
LOG ON
( NAME=QLBHLog,
FILENAME='F:\Bai thuc hanh\CSDL\QLBH.lfd',
SIZE=3MB,
MAXSIZE=5MB,
FILEGROWTH=1MB)
--
USE QLBH
-- Tạo bảng KhachHang
CREATE TABLE KhachHang(
	MaKH NCHAR(5) NOT NULL,
	TenKH NVARCHAR(40) NOT NULL,
	LoaiKH NVARCHAR(3) CHECK (LoaiKH = 'VIP' OR LoaiKH = 'TV' OR LoaiKH = 'VL'),
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(25),
	SoFax NVARCHAR(25),
	DCMail NVARCHAR(50),
	DiemTL INT CHECK (DiemTL >= 0))
-- Tạo bảng HoaDon
CREATE TABLE HoaDon(
	MaHD INT NOT NULL,
	NgayLapHD DATETIME CHECK (NgayLapHD >= (GETDATE())) DEFAULT GETDATE(),
	NgayGiao DATETIME,
	NoiChuyen NVARCHAR(60) NOT NULL,
	MaKH NCHAR(5))
-- Tạo bảng CT_HoaDon
CREATE TABLE CT_HoaDon(
	MaHD INT NOT NULL,
	MaSP INT NOT NULL,
	SoLuong SMALLINT CHECK (SoLuong > 0),
	DonGia MONEY,
	ChietKhau MONEY CHECK(ChietKhau >= 0))
-- Tạo bảng NhaCungCap
CREATE TABLE NhaCungCap(
	MaNCC INT PRIMARY KEY,
	TenNCC NVARCHAR(40) NOT NULL,
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(25),
	SoFax NVARCHAR(25),
	DCMail NVARCHAR(50))
-- Tạo bảng NhomSanPham
CREATE TABLE NhomSanPham(
	MaNhom INT PRIMARY KEY,
	TenNhom NVARCHAR(15))
-- Tạo bảng SanPham
CREATE TABLE SanPham(
	MaSP INT PRIMARY KEY,
	TenSP NVARCHAR(40) NOT NULL,
	MaNCC INT NOT NULL,
	MoTa NVARCHAR(50),
	MaNhom INT NOT NULL,
	DonViTinh NVARCHAR(20),
	GiaGoc MONEY CHECK(GiaGoc > 0),
	SLTon INT CHECK(SLTon > 0),
	CONSTRAINT FK_MaNCC FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
	CONSTRAINT FK_MaNhom FOREIGN KEY (MaNhom) REFERENCES NhomSanPham(MaNhom)
	ON UPDATE CASCADE)
-- Tạo các ràng buộc
ALTER TABLE KhachHang
	ADD CONSTRAINT PK_MaKH PRIMARY KEY (MaKH)
ALTER TABLE CT_HoaDon
	ADD CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
ALTER TABLE CT_HoaDon
	ADD CONSTRAINT FK_MaSP FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
ALTER TABLE CT_HoaDon
	ADD CONSTRAINT FK_MaHD_SP PRIMARY KEY (MaHD,MaSP)
ALTER TABLE HoaDon
	ADD CONSTRAINT PK_MaHD PRIMARY KEY (MaHD)
ALTER TABLE HoaDon
	ADD CONSTRAINT FK_MaKH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
	ON UPDATE CASCADE
ALTER TABLE HoaDon
	ADD LoaiHD CHAR(1) CHECK (LoaiHD = 'N' OR LoaiHD = 'X' OR LoaiHD = 'C' OR LoaiHD = 'T')
ALTER TABLE HoaDon
	ADD CHECK (NgayGiao >= NgayLapHD)